# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf76bf9e63c628a6348145d908b85c6116391497c9da627456ad259ce342f6256a0adc1a78d3b466d321820a2e87bd57dde25b08332ae4e09f3a904ac1fe0b9a

test:
  secret_key_base: 99ffde738e165432e6d248ce8a661ab06135cb1adeb30cff4078087f71f1ec0a1d87ef76e170c422689847bc509a59f988ed79b91908e4fdffe4fc0450e37d9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
